In [1]:
import numpy as np
from sympy import *
init_printing()

U11, U12, U13, U21, U22, U23, U31, U32, U33 = \
symbols('U_11 U_12 U_13 U_21 U_22 U_23 U_31 U_32 U_33')

th1, th2, th3=symbols('theta_1 theta_2 theta_3') #Vacuum mixing angles
C1, C2, C3, S1, S2, S3=symbols('C_1 C_2 C_3 S_1 S_2 S_3')
C1=cos(th1)
C2=cos(th2)
C3=cos(th3)
S1=sin(th1)
S2=sin(th2)
S3=sin(th3)
U11=C2*C3
U12=S3*C2
U13=S2
U21=-S3*C1-S1*S2*C3
U22=C1*C3-S1*S2*S3
U23=S1*C2
U31=S1*S3-S2*C1*C3
U32=-S1*C3-S2*S3*C1
U33=C1*C2
CKM=Matrix([[U11, U12, U13], [U21, U22, U23], [U31, U32, U33]])
CKM

Ue1, Ue2, Ue3, Umu1, Umu2, Umu3, Ut1, Ut2, Ut3 = \
symbols('U_e1 U_e2 U_e3 U_mu1 U_mu2 U_mu3 U_tau1 U_tau2 U_tau3')
CKMgen=Matrix([[Ue1, Ue2, Ue3], [Umu1, Umu2, Umu3], [Ut1, Ut2, Ut3]])
ICKMgen=CKMgen.transpose()


ICKM=simplify(CKM**-1) #Inverse CKM matrix
E1, E2, E3 =symbols('E_1 E_2 E_3')
Hm0=Matrix([[E1, 0, 0], [0, E2, 0], [0, 0, E3]]) #Hamiltonian in mass eigenbase

A=symbols('A') #Matter density
Vf=A*Matrix([[1, 0, 0], [0, 0, 0], [0, 0, 0]])# Perturbation flavor basis
Vf

Vm=ICKMgen*Vf*CKMgen # Perturbation mass basis

Hm=Hm0+Vm
Hm


Id=Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
T=simplify(Hm-(E1+E2+E3+A)/3*Id)
T=T.as_mutable()
E12, E13, E21, E23, E31, E32=symbols('E_12 E_13 E_21 E_23 E_31 E_32')
#E12=E1-E2
#E13=E1-E3
#E21=E2-E1
#E23=E2-E3
#E32=E3-E2
#E31=E3-E1
T[0,0]=T[0, 0]-(2*E1-E2-E3)/3+(E12 + E13)/3
T[1,1]=T[1, 1]-(2*E2-E1-E3)/3+(-E12 + E23)/3
T[2,2]=T[2, 2]-(2*E3-E1-E2)/3+(-E13 - E23)/3

T

lam=symbols('lambda')
char_pol=(lam*Id-T).det()
#char_pol=simplify(char_pol)


char_pol=collect(char_pol, lam, evaluate=False)

c2=char_pol[lam**2]
c0=char_pol[1]
c1=char_pol[lam]
c1=collect(c1, A, evaluate=False)
c1[A**2]=nsimplify(-1./3)
c1=c1[A]*A + c1[1] + c1[A**2]*A**2
c2=0
c0=collect(c0, A, evaluate=False)
c0[A**3]=0
collect(c0[A], E12*E13)

In [2]:
#solve(char_pol, lam)

In [3]:
theta1 = 45. #Degrees
theta2 = 5. #Degrees
theta3 = 45. #Degrees
Ue1 = np.cos(theta2)*np.cos(theta3)
Ue2 = np.sin(theta3)*np.cos(theta2)
Ue3 = np.sin(theta2)
Umu1=-np.sin(theta3)*np.cos(theta1)-np.sin(theta1)*np.sin(theta2)*np.cos(theta3)
Umu2=np.cos(theta1)*np.cos(theta3)-np.sin(theta1)*np.sin(theta2)*np.sin(theta3)
Umu3=np.sin(theta1)*np.cos(theta2)
Ut1=np.sin(theta1)*np.sin(theta3)-np.sin(theta2)*np.cos(theta2)*np.cos(theta3)
Ut2=-np.sin(theta1)*np.cos(theta3)-np.sin(theta2)*np.sin(theta3)*np.cos(theta1)
Ut3=np.cos(theta1)*np.cos(theta2)


In [4]:
numCKM=np.matrix([[Ue1, Ue2, Ue3], [Umu1, Umu2, Umu3], [Ut1, Ut2, Ut3]])
print numCKM


[[ 0.14901398  0.24136915 -0.95892427]
 [-0.01836078  0.97025966  0.24136915]
 [ 0.86692993 -0.01836078  0.14901398]]


In [5]:
A=1e-13 #(1/sqrt(2))*G_f*(1/(m_N*1E-3))*density(L);
numICKM = numCKM.transpose()
V_f=A*np.matrix([[1., 0., 0.], [0., 0., 0.], [0., 0., 0.]])


V_m=numICKM*V_f*numCKM



In [6]:
neutEnergy=1e9
L=1e3
dM32 = 3.2e-3#eV^2
dm21 = 0.#eV^2
E32= dM32/(2.*neutEnergy)
E21= dm21/(2.*neutEnergy)
E12=-E21
E23=-E32
E31=-E12-E23
E13=-E31

In [7]:
traceHM=np.matrix([[(1./3.)*(E12+E13-A), 0., 0.], [0., (1./3.)*(E21+E23-A), 0.],[0., 0., (1./3.)*(E31+E32-A)]])
print traceHM

[[ -5.66666667e-13   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -5.66666667e-13   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.03333333e-12]]


In [8]:
T=V_m+traceHM
print T

[[ -5.64446150e-13   3.59673790e-15  -1.42893126e-14]
 [  3.59673790e-15  -5.60840760e-13  -2.31454740e-14]
 [ -1.42893126e-14  -2.31454740e-14   1.12528691e-12]]


In [9]:
c0=-1.*np.linalg.det(T)
print c0
c2=-1.*T.trace()
print c2
c1=T[0, 0]*T[1, 1]+T[0,0]*T[2,2]+T[1,1]*T[2,2]-T[1,2]*T[2,1]-T[0,1]*T[1,0]-T[0,2]*T[2,0]
print c1
trHm=1e3

-3.56630501911e-37
[[-0.]]
-9.50459055659e-25


In [10]:
q=(1./3.)*c1
r=-(1./2.)*c0
print -c0**2-(4./27)*c1**3
s1ps2=2*np.sqrt(-(1./3)*c1)*np.cos((1./3)*np.arctan((1./c0)*np.sqrt(-c0**2-(4./27)*c1**3)))
s1ms2=-1j*2*np.sqrt(-(1./3)*c1)*np.sin((1./3)*np.arctan((1./c0)*np.sqrt(-c0**2-(4./27)*c1**3)))

1.74249411518e-77


In [11]:
lam1=-(1./2)*s1ps2+1j*np.sqrt(3.)/2 * s1ms2
lam2=-(1./2)*s1ps2-1j*np.sqrt(3.)/2 * s1ms2
lam3=s1ps2
print lam1, lam2, lam3

(-5.66666666667e-13+0j) (-5.59059521768e-13+0j) 1.12572618843e-12


In [12]:
eigValuesT, eigVectsT = np.linalg.eig(T)
eigValuesT

array([  1.12572619e-12,  -5.66666667e-13,  -5.59059522e-13])

In [13]:
def insideSum(lam, L):
    global c1
    global T
    Itty=np.identity(3)
    return 1./(3*lam**2 +c1) * ((lam**2 + c1)*Itty + lam*T + T**2)*np.exp(-1j*L*lam)

def phi(L, trHm):
    Itty=np.identity(3)
    return np.exp(-1j*L*Itty)

In [14]:
def timeOp():
    summ=0.
    global eigValuesT
    global L
    global trHm
    for lamd in eigValuesT:
        summ += insideSum(lamd, L)
        summ *= phi(L, trHm)
    return summ

In [15]:
timeOp()

matrix([[ 0.81310523-0.11856783j,  1.31471671-1.10745345j,
          1.27955212-0.42222399j],
        [ 0.79745731-0.3393574j ,  0.32045541-0.04514719j,
          0.75571439+0.34105091j],
        [ 3.51603901-5.16004913j,  3.50946068-5.16487027j,
          4.34016046-5.06221948j]])

In [16]:
TFsq= numCKM*T**2 *numICKM


In [17]:
TF=numCKM*T*numICKM
term1=(np.real(lam1)**2 + c1)*np.identity(3)
term2=np.real(lam1)*TF
print  term1*1e20+ term2*1e20  + TFsq*1e20

[[ -1.59919820e-18  -4.56381352e-18  -1.14164782e-06]
 [ -4.56720165e-18   3.55282676e-07  -3.64754117e-07]
 [ -1.14164782e-06  -3.64754117e-07  -1.34973435e-05]]


In [18]:
print term1
print term2
print TFsq
print term1[0,0]*1e20+term2[0,0]*1e20+TFsq[0,0]*1e20

[[ -6.29347945e-25  -0.00000000e+00  -0.00000000e+00]
 [ -0.00000000e+00  -6.29347945e-25  -0.00000000e+00]
 [ -0.00000000e+00  -0.00000000e+00  -6.29347945e-25]]
[[ -5.69267982e-25   2.09852298e-25   1.24759367e-25]
 [  2.09852298e-25   2.68289556e-25  -3.18926942e-26]
 [  1.24759367e-25  -3.18926942e-26   2.28423925e-25]]
[[  1.19861593e-24  -2.09852298e-25  -1.36175845e-25]
 [ -2.09852298e-25   3.64611215e-25   2.82451530e-26]
 [ -1.36175845e-25   2.82451530e-26   2.65950585e-25]]
-1.59919820442e-18
